# Generated by Django 5.0.7 on 2024-07-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Business', 'Business'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Sports', 'Sports')], max_length=200),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
